<?php

declare(strict_types=1);

namespace Restify\Support;

use PDO;
use PDOException;
use RuntimeException;

final class Schema
{
    private function __construct()
    {
    }

    public static function ensureLogsTable(PDO $pdo): void
    {
        $driver = self::driver($pdo);

        $sql = match ($driver) {
            'sqlite' => <<<SQL
CREATE TABLE IF NOT EXISTS restify_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    endpoint TEXT NOT NULL,
    request_method TEXT NOT NULL,
    user_data TEXT NOT NULL,
    status_code INTEGER NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
)
SQL,
            'pgsql' => <<<SQL
CREATE TABLE IF NOT EXISTS restify_logs (
    id BIGSERIAL PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL,
    request_method VARCHAR(16) NOT NULL,
    user_data TEXT NOT NULL,
    status_code INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
SQL,
            'sqlsrv' => <<<SQL
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='restify_logs' AND xtype='U')
BEGIN
    CREATE TABLE restify_logs (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        endpoint NVARCHAR(255) NOT NULL,
        request_method NVARCHAR(16) NOT NULL,
        user_data NVARCHAR(MAX) NOT NULL,
        status_code INT NOT NULL,
        created_at DATETIME2 DEFAULT SYSUTCDATETIME()
    );
END;
SQL,
            'oci' => <<<SQL
BEGIN
   EXECUTE IMMEDIATE '
      CREATE TABLE restify_logs (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          endpoint VARCHAR2(255) NOT NULL,
          request_method VARCHAR2(16) NOT NULL,
          user_data CLOB NOT NULL,
          status_code NUMBER(10) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
SQL,
            default => <<<SQL
CREATE TABLE IF NOT EXISTS restify_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL,
    request_method VARCHAR(16) NOT NULL,
    user_data LONGTEXT NOT NULL,
    status_code INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
SQL,
        };

        self::execute($pdo, $sql, $driver);
    }

    public static function ensureTokensTable(PDO $pdo): void
    {
        $driver = self::driver($pdo);

        $sql = match ($driver) {
            'sqlite' => <<<SQL
CREATE TABLE IF NOT EXISTS restify_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    endpoint TEXT NOT NULL,
    token TEXT NOT NULL,
    scheme TEXT NOT NULL,
    algorithm TEXT NOT NULL,
    secret TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
)
SQL,
            'pgsql' => <<<SQL
CREATE TABLE IF NOT EXISTS restify_tokens (
    id BIGSERIAL PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL,
    token TEXT NOT NULL,
    scheme VARCHAR(16) NOT NULL,
    algorithm VARCHAR(16) NOT NULL,
    secret TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
SQL,
            'sqlsrv' => <<<SQL
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='restify_tokens' AND xtype='U')
BEGIN
    CREATE TABLE restify_tokens (
        id BIGINT IDENTITY(1,1) PRIMARY KEY,
        endpoint NVARCHAR(255) NOT NULL,
        token NVARCHAR(MAX) NOT NULL,
        scheme NVARCHAR(16) NOT NULL,
        algorithm NVARCHAR(16) NOT NULL,
        secret NVARCHAR(MAX) NULL,
        created_at DATETIME2 DEFAULT SYSUTCDATETIME()
    );
END;
SQL,
            'oci' => <<<SQL
BEGIN
   EXECUTE IMMEDIATE '
      CREATE TABLE restify_tokens (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          endpoint VARCHAR2(255) NOT NULL,
          token CLOB NOT NULL,
          scheme VARCHAR2(16) NOT NULL,
          algorithm VARCHAR2(16) NOT NULL,
          secret CLOB,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN
         RAISE;
      END IF;
END;
SQL,
            default => <<<SQL
CREATE TABLE IF NOT EXISTS restify_tokens (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    endpoint VARCHAR(255) NOT NULL,
    token TEXT NOT NULL,
    scheme VARCHAR(16) NOT NULL,
    algorithm VARCHAR(16) NOT NULL,
    secret TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
SQL,
        };

        self::execute($pdo, $sql, $driver);
    }

    private static function execute(PDO $pdo, string $sql, string $driver): void
    {
        try {
            $pdo->exec($sql);
        } catch (PDOException $exception) {
            throw new RuntimeException('Schema migration failed: ' . $exception->getMessage(), 0, $exception);
        }
    }

    private static function driver(PDO $pdo): string
    {
        return strtolower((string) $pdo->getAttribute(PDO::ATTR_DRIVER_NAME));
    }
}
